### PR TITLE
Solution to Helper Methods Part 3

### PR DESCRIPTION
**Pull request by bpurinton**
@jelaniwoods. There are two issues that I can't figure out with this solution:

1. When a user fills out the `movies/new` form, if the title is blank then they should be shown the errors associated with the `@movie` object; but these are not being displayed on the page (the `@movie` errors collection is empty)

2. Both "Sign out" and "Delete movie" actions are being made with GET requests, despite the `method: :delete` on both of these `link_to`s. I don't understand why this is happening in Rails 7, but I'm seeing some indication in my searching around online that this has to do with UJS. I'm not really sure how to resolve this / if it is an issue we also need to address in the Rails 7 template.

### CODE REVIEW

**Review by jelaniwoods — COMMENTED** [review]
Both of these issues are related to new Rails 7 defaults (specifically turbo).

> When a user fills out the movies/new form, if the title is blank then they should be shown the errors associated with the @movie object; but these are not being displayed on the page (the @movie errors collection is empty)

This was a little tricky to debug since the console says it renders the template successfully, but the browser actually doesn't update the page. This isn't super obvious because the `create` action is _supposed_ to render the new page.

Two ways you tell that the page did not change are:
- look at the path in the address bar— it stays as `/movies/new` instead of `/movies` (the route for the `create` action).
- the browser console has an error message once you submit the form
   image

To resolve, you need to prevent the form from being processed as a Turbo Stream request. You can do this by adding `data: { turbo: false }` to the `form_with` method.

This appears to only be necessary when you **aren't** using a form partial in your new and edit views like that the scaffold generator creates.

> Both "Sign out" and "Delete movie" actions are being made with GET requests, despite the method: :delete on both of these link_tos. I don't understand why this is happening in Rails 7, but I'm seeing some indication in my searching around online that this has to do with UJS. I'm not really sure how to resolve this / if it is an issue we also need to address in the Rails 7 template.

Another Rails 7 / Turbo default. `method: :delete` does not work for links anymore. Instead you need to use `data: { turbo_method: :delete }`.

```erb
<%= link_to "Delete Movie", @movie,  data: { turbo_method: :delete } %>
```

Does that help?

**Comment by bpurinton** [comment]
@jelaniwoods That resolves things, thanks! I spent too long trying to figure it out. It's too bad about this default, since it adds to the cognitive load in the early Phase 2 projects.. but these are Phase 2 projects after all so I think it's okay to add these `data:` attributes and a little note about Turbo to the lessons.

**Comment by bpurinton** [comment]
@jelaniwoods Is there a simple alternative / hidden way we can flip this setting off in Rails 7 for the first couple of projects? [I'm seeing some answers...](https://stackoverflow.com/questions/70921317/how-can-i-disable-hotwire-turbo-the-turbolinks-replacement-for-all-forms-in)

**Comment by jelaniwoods** [comment]
> Is there a simple alternative / hidden way we can flip this setting off in Rails 7 for the first couple of projects?

As far as I'm aware, there isn't a "built-in" way to turn off turbo for forms.

You can either:
- turn off Turbo entirely and (I assume) re-add the old style turbolinks
- add sme custom JS, as mentioned in the SO thread you poste:
   ```js
  document.addEventListener("turbo:load", function () {
    document.querySelectorAll("form").forEach(function (element) {
      element.dataset.turbo = false
    })
  })
   ```

If students already have to learn about `data: {turbo_method: :delete}` for links I don't think also teaching `data: { turbo: false }` for forms significantly increases cognitive load. I could be missing some context on the direction of the Phase 2 content though.

**Comment by bpurinton** [comment]
>  If students already have to learn about data: {turbo_method: :delete} for links I don't think also teaching data: { turbo: false } for forms significantly increases cognitive load.

I agree. And the solution of turning it off is not satisfactory. Just wanted to see if there was some easy switch to flip as an alternative here.

**Pull request closed without merging**
